paths:
  /Ratings:
    post:
      tags:
        - Rating
      summary: Create a new instance of the model and persist it into the data source.
      operationId: Rating.create
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/Rating'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Rating'
      deprecated: false
    put:
      tags:
        - Rating
      summary: Patch an existing model instance or insert a new one into the data source.
      operationId: Rating.upsert__put_Ratings
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/Rating'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Rating'
      deprecated: false
    patch:
      tags:
        - Rating
      summary: Patch an existing model instance or insert a new one into the data source.
      operationId: Rating.upsert__patch_Ratings
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/Rating'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Rating'
      deprecated: false
    get:
      tags:
        - Rating
      summary: Find all instances of the model matched by filter from the data source.
      operationId: Rating.find
      parameters:
        - name: filter
          in: query
          description: 'Filter defining fields, where, include, order, offset, and limit - must be a JSON-encoded string ({"something":"value"})'
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: array
            items:
              $ref: '#/definitions/Rating'
      deprecated: false
  /Ratings/replaceOrCreate:
    post:
      tags:
        - Rating
      summary: Replace an existing model instance or insert a new one into the data source.
      operationId: Rating.replaceOrCreate
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/Rating'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Rating'
      deprecated: false
  /Ratings/upsertWithWhere:
    post:
      tags:
        - Rating
      summary: Update an existing model instance or insert a new one into the data source based on the where criteria.
      operationId: Rating.upsertWithWhere
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            description: An object of model property name/value pairs
            $ref: '#/definitions/Rating'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Rating'
      deprecated: false
  '/Ratings/{id}/exists':
    get:
      tags:
        - Rating
      summary: Check whether a model instance exists in the data source.
      operationId: 'Rating.exists__get_Ratings_{id}_exists'
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              exists:
                type: boolean
      deprecated: false
  '/Ratings/{id}':
    head:
      tags:
        - Rating
      summary: Check whether a model instance exists in the data source.
      operationId: 'Rating.exists__head_Ratings_{id}'
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              exists:
                type: boolean
      deprecated: false
    get:
      tags:
        - Rating
      summary: 'Find a model instance by {{id}} from the data source.'
      operationId: Rating.findById
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
        - name: filter
          in: query
          description: 'Filter defining fields and include - must be a JSON-encoded string ({"something":"value"})'
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Rating'
      deprecated: false
    delete:
      tags:
        - Rating
      summary: 'Delete a model instance by {{id}} from the data source.'
      operationId: Rating.deleteById
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
      deprecated: false
    put:
      tags:
        - Rating
      summary: Patch attributes for a model instance and persist it into the data source.
      operationId: 'Rating.prototype.updateAttributes__put_Ratings_{id}'
      parameters:
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            description: An object of model property name/value pairs
            $ref: '#/definitions/Rating'
        - name: id
          in: path
          description: Rating id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Rating'
      deprecated: false
    patch:
      tags:
        - Rating
      summary: Patch attributes for a model instance and persist it into the data source.
      operationId: 'Rating.prototype.updateAttributes__patch_Ratings_{id}'
      parameters:
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            description: An object of model property name/value pairs
            $ref: '#/definitions/Rating'
        - name: id
          in: path
          description: Rating id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Rating'
      deprecated: false
  '/Ratings/{id}/replace':
    post:
      tags:
        - Rating
      summary: Replace attributes for a model instance and persist it into the data source.
      operationId: Rating.replaceById
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/Rating'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Rating'
      deprecated: false
  /Ratings/findOne:
    get:
      tags:
        - Rating
      summary: Find first instance of the model matched by filter from the data source.
      operationId: Rating.findOne
      parameters:
        - name: filter
          in: query
          description: 'Filter defining fields, where, include, order, offset, and limit - must be a JSON-encoded string ({"something":"value"})'
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Rating'
      deprecated: false
  /Ratings/update:
    post:
      tags:
        - Rating
      summary: 'Update instances of the model matched by {{where}} from the data source.'
      operationId: Rating.updateAll
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            description: An object of model property name/value pairs
            $ref: '#/definitions/Rating'
      responses:
        '200':
          description: Request was successful
          schema:
            description: Information related to the outcome of the operation
            type: object
            properties:
              count:
                description: The number of instances updated
                type: number
                format: double
      deprecated: false
  /Ratings/count:
    get:
      tags:
        - Rating
      summary: Count instances of the model matched by where from the data source.
      operationId: Rating.count
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              count:
                type: number
                format: double
      deprecated: false
  /Ratings/CustomAPI:
    post:
      tags:
        - Rating
      operationId: Rating.customAPIEndpoint
      parameters:
        - name: msg
          in: formData
          required: false
          type: string
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              return:
                type: string
      deprecated: false
  /Inventories:
    get:
      tags:
        - Inventory
      summary: Find all instances of the model matched by filter from the data source.
      operationId: Inventory.find
      parameters:
        - name: filter
          in: query
          description: 'Filter defining fields, where, include, order, offset, and limit - must be a JSON-encoded string ({"something":"value"})'
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: array
            items:
              $ref: '#/definitions/Inventory'
      deprecated: false
definitions:
  Rating:
    properties:
      id:
        type: string
    additionalProperties: false
  x-any:
    properties: {}
  Inventory:
    properties:
      id:
        type: string
    additionalProperties: false
basePath: /api
swagger: '2.0'
info:
  x-ibm-name: funwithwakefern
  version: 1.0.0
  title: FunWithWakefern
schemes:
  - https
host: $(catalog.host)
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
  clientSecretHeader:
    in: header
    name: X-IBM-Client-Secret
    type: apiKey
security:
  - clientIdHeader: []
    clientSecretHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  catalogs:
    apic-dev:
      properties:
        runtime-url: $(TARGET_URL)
    sb:
      properties:
        runtime-url: 'http://localhost:4001'
  assembly:
    execute:
      - invoke:
          target-url: $(runtime-url)$(request.path)$(request.search)
